### ISSUE TITLE
Landscape orientation not working properly

### ISSUE THREAD

**Issue by 3ph** [apivideo/api.video-flutter-live-stream#12]
When the phone is landscape orientated the stream is still in a weird distorted portrait mode - only cut out "zoomed" middle portion of the screen is visible with portrait aspect ratio.

I've tested on iOS.

**Comment by ThibaultBee** [comment]
Hi,

I have made a fix on the master branch. Could you test it?

**Comment by 3ph** [comment]
@ThibaultBee Thanks for the fix! I actually found a solution yesterday as well here https://github.com/shogo4405/HaishinKit.swift/issues/147#issuecomment-266889004

It's working great.

**Comment by ThibaultBee** [comment]
Ok, thanks for the reply :)
We will release a new version soon.

**Comment by ThibaultBee** [comment]
Ok, the fix has been released in v1.0.5.
Tell us if you face any issue.

Best regards,
Thibault
