### ISSUE TITLE
Bug: AudioConverter inconsistent packets

### ISSUE THREAD

**Issue by Zechst** [apivideo/api.video-flutter-live-stream#15]
After following the example, the debugConsole is returning  this line 
`[AudioConverter] CompositeAudioConverter.cpp:1239  Input data proc returned inconsistent 1 packets for 2048 bytes; at 2 bytes per packet, that is actually 1024 packets`

1.  controller was created in this format
```
      textureId = controller.create(
        initialAudioConfig: AudioConfig(),
        initialVideoConfig: VideoConfig.withDefaultBitrate(),
      );
```

Not sure if this should be printing

![Screenshot 2022-09-23 at 12 03 48 PM](https://user-images.githubusercontent.com/38596941/191890171-781c8149-8499-4dab-bf47-6f0f4d58f6a9.png)

 - Device: iPhone 11 Pro Max
 - OS: iOS 16

Should I be receiving a packet error? Please assist, thank you

**Comment by ThibaultBee** [comment]
Hi,

It seems there has been some fixes on our iOS native live streaming library. See https://github.com/shogo4405/HaishinKit.swift/issues/1016. Thanks for noticing!
We will update soon.

**Comment by ThibaultBee** [comment]
Hi,

I updated HK in the main branch. Could you check if the message still appears?

**Comment by Zechst** [comment]
Hi, is this in the new release update for flutter package?

**Comment by ThibaultBee** [comment]
Not yet. Waiting to fix more issues before releasing.

**Comment by Zechst** [comment]
Ok thank you. I will wait for the release to test and see if it still logs the error

**Comment by ThibaultBee** [comment]
1.0.6 has been released. Could you verified that this issue has been fixed?

**Comment by Zechst** [comment]
Hi, thanks so much. The error is no longer seen :)
