### ISSUE TITLE
Unable to use Resolution.RESOLUTION_1080

### ISSUE THREAD

**Issue by AlexNik4** [apivideo/api.video-flutter-live-stream#16]
**Describe the bug**
Crash when attempting to stream in 1080p

**To Reproduce**
1. Change the VideoConfig.withDefaultBitrate(); to VideoConfig.withDefaultBitrate(resolution: Resolution.RESOLUTION_1080, fps: 30); in the params.dart class of the example.
2. Run the example project and try to stream

**Expected behavior**
Streaming with the 1080p resolution should not crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/53029348/192202517-7b5d9f16-bdff-4e6d-b6db-3e0f7f73d028.png)

**Smartphone (please complete the following information):**
 - Pixel 6

**Additional context**
I think the "p" is missing when specifying 1080p like for other resolutions. When I update the following locally, I was able to successfully stream in 1080p:
lib/src/types/resolution.dart -> Change the @JsonValue from "1080" to "1080p"
lib/src/types/video_config.g.dart -> Resolution.RESOLUTION_1080: '1080p'   again just adding the "p"

I would make a PR but not sure where the source of the auto generated file is.

**Comment by ThibaultBee** [comment]
Hello :)
Oops. Sorry for this issue.
The file `lib/src/types/video_config.g.dart` is generated by the `build_runner` package.
Anyway, I just fixed it.

**Comment by AlexNik4** [comment]
Thanks for the quick fix! Just wondering when a new package may be released.

**Comment by ThibaultBee** [comment]
1.0.6 has been released. Could you verified?

**Comment by AlexNik4** [comment]
LGTM
