### ISSUE TITLE
Question  

### ISSUE THREAD

**Issue by LucGamesYT** [apivideo/api.video-flutter-live-stream#23]
Hey I have a question I have problems with the display of the Livestream why is the video in the stream so small ?

And my second question is if you can use the api to add a stream overlay for example or show other stuff ?

![image](https://user-images.githubusercontent.com/19286296/206199559-c191dff1-b5a0-47c0-972a-61d947a863f5.png)

**Comment by ThibaultBee** [comment]
Hi,
I am not going to be really helpfull here.

For your first question, I honestly don't know. If you figures why, please share the answer with everyone.
For your second question, there is not such API. You can switch to the front camera if you want to show other stuff.

For reference purpose, could you share the following information?
- your phone and OS
- your video and audio configuration
