### ISSUE TITLE
WEB Support

### ISSUE THREAD

**Issue by Akshay-akkay** [apivideo/api.video-flutter-live-stream#24]
**Is your feature request related to a problem? Please describe.**
This is amazing package but there are no support web, even tho api.video supports it in JS ecosystem. 
I have been trying to broadcast to rtmp on flutter web on my own using websockets as transfer protocol and ffmpeg for trancoding on a proxy server, But not able to do yet.

**Describe the solution you'd like**
There is a package for Native Web(JS) on NPM for doing the same [@api.video/browser-to-rtmp-client](https://www.npmjs.com/package/@api.video/browser-to-rtmp-client?activeTab=readme#client-side-part) .
It would be awesome, if we could port it to flutter web.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ThibaultBee** [comment]
Hi,

That would be really nice. Unfortunately as you said, it would required a third party server (from WebSocket to RTMP). This is not something we want to include in our live stream libraries.
So, we won't add that feature as long as it is not possible to directly stream RTMP from browser.
