### ISSUE TITLE
Android does not respond to the provided bitrate

### ISSUE THREAD

**Issue by brauliolomeli** [apivideo/api.video-flutter-live-stream#27]
Android streams at a bitrate between 4000000 and 7000000 even when the provided bitrate in the VideoConfig is 2000000.

**To Reproduce**
1. Stream from an Android device with resolution Resolution.RESOLUTION_720 and bitrate 2000000.

**Expected behavior**
Streams at 2000000 bps

**Comment by brauliolomeli** [comment]
Possibly related:
https://github.com/ThibaultBee/StreamPack/issues/64

**Comment by ThibaultBee** [comment]
Hi,

As you have close the issue in StreamPack, could you close this one as well?

**Comment by ThibaultBee** [comment]
As https://github.com/ThibaultBee/StreamPack/issues/64 has been closed also closing this one.
