### ISSUE TITLE
error Thread in crash app

### ISSUE THREAD

**Issue by rezadevelopers2** [apivideo/api.video-flutter-live-stream#3]
Thread[2,tid=25421,WaitingInMainSignalCatcherLoop,Thread*=0x7378a04000,peer=0x13100238,"Signal Catcher"]: reacting to signal 3

Wrote stack traces to tombstoned

**Comment by ThibaultBee** [comment]
Hi there,

We can't help you with this little information.
Please, open a new bug and use the `Bug report`.

Regards,
Thibault
