### ISSUE TITLE
[Feat]: getting srt stream from different cameras and broadcast to rtpm

### ISSUE THREAD

**Issue by drunkod** [apivideo/api.video-flutter-live-stream#32]
### Version

last

### Environment that reproduces the issue

android

### Use case description

Please give advice step by step how to add support getting srt stream from different cameras and broadcast to rtpm.

**Comment by ThibaultBee** [comment]
Hi there,

This library streams camera and microphone frames over RTMP for Android and iOS.
What you are looking to do would have to be perform on a server, therefore it is not related to this library.

**Comment by drunkod** [comment]
> Hi there,
> 
> This library streams camera and microphone frames over RTMP for Android and iOS. What you are looking to do would have to be perform on a server, therefore it is not related to this library.

Good afternoon.
Please give a couple of tips on how to correctly implement this function, of course, in the fork of your code.
