### ISSUE TITLE
[Bug]: Ios is crashed when another application is using microphone

### ISSUE THREAD

**Issue by nhat108** [apivideo/api.video-flutter-live-stream#34]
### Version

v1.1.1

### Which operating systems have you used?

- [ ] Android
- [X] iOS

### Environment that reproduces the issue

Iphone 12

### Is it reproducible in the example application?

Yes

### RTMP Server

api.video

### Reproduction steps

1. Config livestream
2. check microphone permission is denined
3. start livestream -> crash

### Expected result

![image](https://github.com/apivideo/api.video-flutter-live-stream/assets/40523356/efbc2bd8-f421-4479-a495-e7938b6427d0)

### Actual result

com.haishinkit.HaishinKit.AudioIOComponent.lock', stop reason = Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value
    frame #1: 0x0000000105c4b1f4 HaishinKit`AudioCodec.converter.getter(self=<unavailable>) at AudioCodec.swift:171:26 [opt]
   168 	        if status != noErr {
   169 	            logger.warn("\(status)")
   170 	        }
-> 171 	        return _converter!
    	                         ^
   172 	    }
   173
   174 	    /// Encodes bytes data.

**Comment by ThibaultBee** [comment]
Hi,

I tried to reproduce your issue with the example but could not face it. See the video above.
![output](https://github.com/apivideo/api.video-flutter-live-stream/assets/37510686/00da961e-ec4a-457d-8cc7-305c427e10b5)

Am I missing something?

**Comment by ThibaultBee** [comment]
I tried with the native recorder but it did not crash either. Could test it?

**Comment by ThibaultBee** [comment]
Have you tried directly with latest version of HaishinKit?

**Comment by ThibaultBee** [comment]
Hi,

The HaishinKit version has been updated on the `main` branch.
Could you test that it fixes this issue?

**Comment by ThibaultBee** [comment]
Stalled issue -> Closing.
Feel free to repoen the issue if you still need support.
