### ISSUE TITLE
[Bug]: Unable to interact with app after stopPreview

### ISSUE THREAD

**Issue by kodypeterson** [apivideo/api.video-flutter-live-stream#36]
### Version

v1.1.1

### Which operating systems have you used?

- [ ] Android
- [X] iOS

### Environment that reproduces the issue

iPhone 11 (iOS 16.3.1)

### Is it reproducible in the example application?

No

### RTMP Server

N/A

### Reproduction steps

Not reproducible in sample app due to no ability to stop/start preview

1. Start preview
2. Stop preview
3. Start preview
4. Flutter app is now not intractable for 10-15 seconds, all interactions during this time playback after the delay.

Interestingly, the preview for the camera does appear and is live, although it does stutter during the 10 - 15 seconds.

### Expected result

Application is intractable during entire flow.

### Actual result

See steps

**Comment by ThibaultBee** [comment]
Hi,

I hack the example to call:
- `stopPreview` when click on mic button
- `startPreview` when click on switch camera button

See https://github.com/apivideo/api.video-flutter-live-stream/tree/test/stop_start_preview

Unfortunately I can't reproduce the issue. 

Is there a way to have access to a code that reproduce it?

**Comment by kodypeterson** [comment]
We identified this as an issue with the way that we were storing the controller in bloc. After stopping the preview we now also null out our controller and start with a new controller. Not exactly sure what causes this still, but likely to do with something around Equatable and Bloc than this library.
