### ISSUE TITLE
Camera doesn't dispose

### ISSUE THREAD

**Issue by luis901101** [apivideo/api.video-flutter-live-stream#4]
**Describe the bug**
The camera keeps engaged after `_controller.stop();` in iOS, not tested it in Android. In iOS, a green dot is shown in the upper right corner of the screen while the camera is in use. When I start streaming the `CameraPreview` connects to the camera hardware but after I stop streaming and stop preview, the camera preview keeps alive, and the green dot still shown.
I have to completely close the app for the camera to be released.

**To Reproduce**
1. Start CamerPreview
2. Start Streaming
3. Stop Camera Preview
4. Stop Streaming 

**Expected behavior**
Camera usage to be released.

**Screenshots**

**Smartphone (please complete the following information):**
 - Devices: iPad 6th gen and iPhone 12
 - OS: both with iOS 15.5

**Comment by ThibaultBee** [comment]
Hi,

Thank you for reporting this issue.
Could you test the fix: https://github.com/apivideo/api.video-flutter-live-stream/commit/b9204d76b5bf3711064a4e3198111270214b69f0?

Best regards,
Thibault

**Comment by ThibaultBee** [comment]
Hi,

We just published new 1.0.2 release. I am closing this issue, feel free to reopen it if needed.

Best regards,
Thibault
