### ISSUE TITLE
[Feat]: Does this package work with other RMTP endpoints not api.video ones?

### ISSUE THREAD

**Issue by LucaJeevanjee** [apivideo/api.video-flutter-live-stream#46]
### Version

1.1.3

### Environment that reproduces the issue

Using on ios 17
Flutter Latest

### Use case description

Im trying to connect to a Mux livestream to broadcast to it yet it is not working. I am getting no OnConnection, OnError or any other messages from the controller.

**Comment by ThibaultBee** [comment]
Hi,

Well, it is supposed to work on most of the RTMP endpoints.
Pretty sure, some user already used this library to stream to Mux.

But I haven't tested this version on iOS 17.

Do you have the same issue with Android?

**Comment by ThibaultBee** [comment]
Is this issue solved?

**Comment by ThibaultBee** [comment]
Stalled issue -> Closing.
