### ISSUE TITLE
[Issue]: Encountering an Exception when streaming Time in Flutter. Error Message: 'PlatformException(failed_to_start_stream, java.lang.IllegalArgumentException: Only one audio stream is supported by FLV, null, null)'.

### ISSUE THREAD

**Issue by Ajmalnk1836** [apivideo/api.video-flutter-live-stream#51]
### Version

v1.1.1

### Which operating systems have you used?

- [X] Android
- [ ] iOS

### Environment that reproduces the issue

Google Pixel 5, POCO X2

### Is it reproducible in the example application?

Yes

### RTMP Server

api.video

### Reproduction steps

Configure video for 720p, Start the stream 

### Expected result

want to play stream very well without throwing exception, Currently encountering an Exception when streaming Time in Flutter. is like Error Message: 'PlatformException(failed_to_start_stream, java.lang.IllegalArgumentException: Only one audio stream is supported by FLV, null, null)',

I wan to resolve this issue, Hope some one can resolve this issue

### Actual result

The Player throwing exception following one,Error Message: 'PlatformException(failed_to_start_stream, java.lang.IllegalArgumentException: Only one audio stream is supported by FLV, null, null)',

### Additional context

flutter version : 3.19.4

### Relevant logs output

```shell
Exception log:
PlatformException(failed_to_start_stream, java.lang.IllegalArgumentException: Only one audio stream is supported by FLV, null, null)',
```

**Comment by ThibaultBee** [comment]
We don't enough information to find the root cause of the issue.
If I run the example in 720p and click on the start stream button, I won't face this issue.
Could you described the actions (for the example) or the API calls precisely?

**Comment by ThibaultBee** [comment]
Hi,

For reference, how did you proceed to fix it?

Best regards,
Thibault
