### ISSUE TITLE
[Bug]: Tutorial not working on latest flutter stable version

### ISSUE THREAD

**Issue by yieniggu** [apivideo/api.video-flutter-live-stream#52]
### Version

v1.1.1

### Which operating systems have you used?

- [x] Android
- [ ] iOS

### Environment that reproduces the issue

Android 13, Xiaomi 10c

### Is it reproducible in the example application?

Yes

### RTMP Server

hasn't even come to that part

### Reproduction steps

Just trying the example from https://api.video/blog/tutorials/build-your-flutter-live-streaming-application-with-api-video/

### Expected result

Init the app

### Actual result

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apivideo_live_stream:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

**Comment by ThibaultBee** [comment]
Hi,

Thanks for reporting this issue.

- Could write the whole compilation error?
- In which part of the tutorial are you stuck?

**Comment by ThibaultBee** [comment]
From what I see, it could be because Flutter project default Kotlin version is `1.7.10`.
In this case, in `android/settings.gradle`, replace in the `plugins` sections:
```
id "org.jetbrains.kotlin.android" version "1.7.10" apply false
```
by
```
id "org.jetbrains.kotlin.android" version "1.9.0" apply false
```

**Comment by yieniggu** [comment]
Thanks, that worked!
