### ISSUE TITLE
[Feat]: Streaming not only the video, but also the image on top of it

### ISSUE THREAD

**Issue by Skrip0v** [apivideo/api.video-flutter-live-stream#61]
### Version

1.2.0

### Environment that reproduces the issue

Iphone 13, iOS 17.5.1

### Use case description

Is it possible to broadcast live not only the video that comes from the `ApiVideoCameraPreview`, but also add more on top of this video - for example, an advertising banner that could be placed at the bottom in the corner, or some kind of picture on top of the video. Or, for example, put a link to a donation widget at the top of the video, which will display donations?

Is it possible to implement this somehow with the current version of the package?

**Comment by Skrip0v** [comment]
Here is an example of how I would like to broadcast a banner live. Is it possible to do this?
![IMG_E5422827BD25-1](https://github.com/apivideo/api.video-flutter-live-stream/assets/93714842/e924c489-ea0b-4e7b-bf9e-e9a43b5b855b)

**Comment by ThibaultBee** [comment]
It is not possible with the current version.
It is a lot of work and specially works with OpenGL.

i doubt we will add this feature in this package.

Morover, I have the feeling this part should be done on the server or player side instead of in this package.
