### ISSUE TITLE
How do we get the live-stream video URL Flutter?

### ISSUE THREAD

**Issue by haraprasad12345** [apivideo/api.video-flutter-live-stream#62]
### Version

v1.2.0

### Which operating systems have you used?

- [X] Android
- [X] iOS

### Environment that reproduces the issue

How to get the live stream video URL.

### Is it reproducible in the example application?

Yes

### RTMP Server

How to get the live stream video URL.

### Reproduction steps

How do we get the live-stream video URL?

### Expected result

Video URL

### Actual result

Video Link

**Comment by ThibaultBee** [comment]
This package is for publishing a RTMP live stream, not for playing a video.

All you need is a URL and a Stream key. These info are provided by your video server.

**Comment by Karthik-flutterDev** [comment]
How can we test it locally?
