### ISSUE TITLE
[Bug]: Android build error | flutter v3.22.1

### ISSUE THREAD

**Issue by imsujan276** [apivideo/api.video-flutter-live-stream#66]
### Version

v1.2.0

### Which operating systems have you used?

- [X] Android
- [ ] iOS

### Environment that reproduces the issue

Google Pixel 5 Api 31 simulator

### Is it reproducible in the example application?

Yes

### RTMP Server

api.video

### Reproduction steps

1. use flutter v3.22.1
2. build app using "flutter build appbundle --release"

### Expected result

The app should build successfully

### Actual result

The app build fails with an error stack below

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':apivideo_live_stream'.
> java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to release lock on instrumented jar cache
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':apivideo_live_stream' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':native_device_orientation'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not get unknown property 'android' for project ':apivideo_live_stream' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Running Gradle task 'bundleProdRelease'...                         12.0s
Gradle task bundleProdRelease failed with exit code 1
make: *** [appbundle] Error 1
```

### Additional context

Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (3 months ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3

**Comment by ThibaultBee** [comment]
Hi,

The error is `Failed to release lock on instrumented jar cache`.
As there is a lock involved, have you tried to clean your build?

I also run `flutter build appbundle --release` without error on my side.

**Comment by imsujan276** [comment]
Yes I tried flutter clean too. Still got that error

**Comment by ThibaultBee** [comment]
Could you clone again that repo?

**Comment by imsujan276** [comment]
I upgraded the flutter to latest version and it cworked

**Comment by ThibaultBee** [comment]
Then I am closing this issue.
