### ISSUE TITLE
Screen Share

### ISSUE THREAD

**Issue by ting28418** [apivideo/api.video-flutter-live-stream#70]
### Version

apivideo_live_stream: ^1.2.0

### Environment that reproduces the issue

I am currently using the api.video-flutter-live-stream package for a Flutter project and was wondering if there are any plans to add a screen-sharing feature in the near future.

### Use case description

Screen sharing would be a valuable addition to the package, especially for apps involving live streaming of presentations, tutorials, or gameplay. If this feature is on the roadmap, I would love to know more about its expected release timeline.

Thank you for your time and for maintaining such a great package! I look forward to your response.

**Comment by ThibaultBee** [comment]
Duplicates https://github.com/apivideo/api.video-flutter-live-stream/issues/60
