### ISSUE TITLE
[Question] Why are you using StreamPack & HaishinKit. If HaishinKit support both Android and iOS

### ISSUE THREAD

**Issue by Aminadav** [apivideo/api.video-flutter-live-stream#71]
It make the app much bigger in size. Why need both libraries?

**Comment by ThibaultBee** [comment]
Hi there,

HK does not support both Android and iOS, there are one HK library for Swift (HK.swift) and another one for Android (HK.kt). There are not the same libraries. We will required them both in this project.

Also, at the point we started the flutter dev, HK.kt does not seem stable.
Last reason is it is easier for us to make changes in StreamPack.
