### ISSUE TITLE
Enabling other video encodings.

### ISSUE THREAD

**Issue by RickyvdBerg** [apivideo/api.video-flutter-live-stream#9]
**Is your feature request related to a problem? Please describe.**
Default example and own implementation do not work out of the box with node-media-server. Only the AAC audio arrives.

**Describe the solution you'd like**
Maybe changing the video codec to H.264 solves this, since it is also supported by the underlying package streampack for android.

**Describe alternatives you've considered**
Tried adding the mimeType to the VideoConfig and enabling it myself.

**Comment by ThibaultBee** [comment]
Hi,

By default StreamPack is in h.264/AVC and this is what we are using. Thus the error you face is not related to the video encoder type.

Could you try to live stream locally with:
`ffplay -listen 1 -i rtmp://0.0.0.0:1935/s/streamKey`
and the url in the example to: `rtmp://your.computer.ip:1935/s/` and check if it streams video and audio.

**Comment by RickyvdBerg** [comment]
Just tested it and it seems video is coming through. It shows:

` Stream #0:1: Video: h264 (High), yuv420p(progressive), 720x1280, 2048000 kb/s, 30 fps, 29.97 tbr, 1k tbn`

Honestly I am not very well versed in the whole media encoding and media protocol world, so I am at a loss of why it wouldn't work with node-media-server. Thanks for the response.

**Comment by ThibaultBee** [comment]
Was the video displayed? A SDL window should open (sometimes in background)

**Comment by RickyvdBerg** [comment]
No, nothing opened. Is there a way to output it in a file. I tried to look it up but didn't really get it to work.

**Comment by RickyvdBerg** [comment]
This is the full result:

![image](https://user-images.githubusercontent.com/5526526/173312268-de98af7a-21bd-41ee-adf5-723ae7f7c7df.png)

**Comment by ThibaultBee** [comment]
I don't see any error there. 
How did you generate the file?
Could you add the file to the issue?

**Comment by RickyvdBerg** [comment]
I ran ` .\ffmpeg.exe -listen 1 -i rtmp://0.0.0.0:1935/live/stream ./video.mp4` 
and Il see if I can make a new file.

**Comment by ThibaultBee** [comment]
Hum, with this command ffmpeg transmuxes the RTMP frames to MP4 boxes... I will check if we can get the raw stream frame.

**Comment by RickyvdBerg** [comment]
Is there any other way to get the raw stream into video? Because just running the command without a video output file doesn't work.

**Comment by ThibaultBee** [comment]
Let's start with:
`ffmpeg -i rtmp://0.0.0.0:1935/live/stream -acodec copy -vcodec copy c:/video.mp4`
Just to check the raw H.264 frames.

Then, we might use `rtmpsuck` or `rtmpsrv`.

**Comment by RickyvdBerg** [comment]
Hmm this gives me an error.
![image](https://user-images.githubusercontent.com/5526526/173317856-c593c5f6-7510-4de3-a06d-6e21752507fd.png)

**Comment by ThibaultBee** [comment]
Sorry, I forgot the `-listen 1`:
`.\ffmpeg.exe -listen 1 -i rtmp://0.0.0.0:1935/live/stream -acodec copy -vcodec copy ./video.mp4`

**Comment by RickyvdBerg** [comment]
![image](https://user-images.githubusercontent.com/5526526/173319270-43e59964-8814-430f-8862-9836b5eff63d.png)

No problem, it looks like 0 headers were send?

**Comment by ThibaultBee** [comment]
hum. I don't know why the "Immediate exit requested" was triggered and what does it mean :(

**Comment by RickyvdBerg** [comment]
I stopped it in order to obtain the file. It was a manual ctrl + c or it would be stuck in the cmd.

**Comment by ThibaultBee** [comment]
Ok, the `video.mp4` file should be in your folder. Can add it to this issue?

**Comment by RickyvdBerg** [comment]
https://user-images.githubusercontent.com/5526526/173331296-4a1c8890-9af9-4d7a-ac6c-ebb580305b02.mp4

here it is

**Comment by ThibaultBee** [comment]
You have to press `q` to end the stream with ffmpeg. Otherwise you will miss the MOOV box that contains information to read the stream (such as frame offset).
Could you capture a stream again and press `q` then send me the file please?

**Comment by RickyvdBerg** [comment]
I did try this, however It didnt want to exit by pressing just q.

**Comment by RickyvdBerg** [comment]
https://user-images.githubusercontent.com/5526526/173337369-5733fa3f-ffde-4f39-8d5d-b5ff3773220b.mp4

Opening it now doesnt give an error, but still no video just a seeker.

**Comment by ThibaultBee** [comment]
I can read the video with ffplay but can't play it with VLC... I don't see any error with VLC...

**Comment by ThibaultBee** [comment]
Well, with:
```
ffplay -listen 1 -i rtmp://0.0.0.0:1935/s/streamKey
```

I can directly play the live stream

**Comment by RickyvdBerg** [comment]
Allright so I did a clean build and with both the default example app and my own implementation. A window pops up from ffplay with the stream. However both do not want to communicate with node-media-server. So it might just be an incompatibility issue with node-media-server. Which i still find odd as other libraries using h264 with rtmp seem to work with node-media-server.

**Comment by ThibaultBee** [comment]
Could you test with https://github.com/apivideo/api.video-flutter-live-stream/tree/test/encoder?

**Comment by RickyvdBerg** [comment]
yes il do it right away!

**Comment by RickyvdBerg** [comment]
Getting the exact same result, with the test branch.
Some other example apps like this native android one https://github.com/begeekmyfriend/yasea did work out of the box with node media server.

**Comment by ThibaultBee** [comment]
You don't change the encoder type by setting the profile and the level.
On ffplay, you can see the encoding profile:
- Video: h264 (**Baseline**)
- Video: h264 (**High**)

Unfortunately, I don't see what I can do for this issue. Could you contact node media developer as well?

**Comment by RickyvdBerg** [comment]
Yeah understandable, thanks for looking at it though.

**Comment by ThibaultBee** [comment]
Hey,

I know it has been a while...
I made fixes in our Android RTMP library: https://github.com/ThibaultBee/StreamPack (branch develop)
Could you test it please?

Regards,
Thibault

**Comment by ThibaultBee** [comment]
Hi,

We have made and released fixes for RTMP/FLV compatibility. It should now works with more RTMP servers.
Unfortunately, it is not going to work with Node Media Server because RTMP requires timestamp to be in order. It is not the case on our live stream library because audio frames are encoded faster than video frames.

There aren't any proper solution:

- We could create new frame timestamp for current device clock but it will create a desync between audio and video (solution use by yasea)
- Wait to get the old frame before sending the new frames but it will increase latency and it is very hard to implement.

So, instead of choosing a bad solution, we prefer to keep it our way. Unfortunately, this library won't be supported by Node Media Server.

Best regards,
Thibault
